FROM centos:centos7
# Set the working directory to /app
#WORKDIR /app

# Copy the current directory contents into the container at /app
# ADD . /app

RUN yum -y install iproute net-tools;
RUN yum -y install epel-release;
RUN yum -y install nginx;
RUN systemctl enable nginx;


CMD [ "/usr/sbin/init" ]
